service: slack-sms
frameworkVersion: '3'
package:
  artifact: ./function.zip
provider:
  name: aws
  runtime: nodejs14.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    NOTIFICATION_CHANNEL: ${env:NOTIFICATION_CHANNEL}
    TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
    TWILIO_NUMBER: ${env:TWILIO_NUMBER}
    HARMONYSITE_USERNAME: ${env:HARMONYSITE_USERNAME}
    HARMONYSITE_PASSWORD: ${env:HARMONYSITE_PASSWORD}
functions:
  slack:
    handler: dist/index.handler
    events:
      - http:
          path: slack/events
          method: post
